### ISSUE TITLE
`createprismrune` plugin method

### ISSUE THREAD

**Issue by gudnuf** [gudnuf/bolt12-prism#12]
This would be a plugin method that creates a rune with specified privelages

**Comment by farscapian** [comment]
Just some thoughts on this. There are multiple types of runes that you might produce. For example, a Prism Reader who can list and read all prisms. Or maybe a rune that is a Prism Reader--but only for specific prisms. Similar for Prism creading/update. Runes should be produced according to least privilege whenever possible.

**Comment by farscapian** [comment]
Rune construction is outside the scope of the prism project.
