### ISSUE TITLE
`prismstatus` plugin method

### ISSUE THREAD

**Issue by gudnuf** [gudnuf/bolt12-prism#13]
This would return the status of a specified prism.

We would want to keep track of payment failures and do some accounting.

The node operator should be able to:
1. get prism status from node
2. look at any failed payments + how much each offer is owed
3. be able to look at logs related to payment failure 

Basically, we want to help the node operator resolve any failed payouts

**Comment by farscapian** [comment]
Prism status is now under prism-bindinglust. Logging is taken care of in the plugin.
