### ISSUE TITLE
Add option for "self-payment" for fee collection

### ISSUE THREAD

**Issue by gudnuf** [gudnuf/bolt12-prism#45]
- [ ] add a startup option to specify different fees
- [ ] calculate what pay-to-self split would be based on total splits and set fee rate
- [ ] if "name" is a self-payment, then just log to self-pays, but do not pay anything (by not paying, the prism node is collecting a fee and essentially paying to self)

**Comment by farscapian** [comment]
This is currently implemented as the outlay_factor in prism v2
