### ISSUE TITLE
If a payment is not completed immediatley, then outlay will not be updated

### ISSUE THREAD

**Issue by gudnuf** [gudnuf/bolt12-prism#47]
This may require us to subscribe to outgoing payments then check its paying any outstanding funds

**Comment by daGoodenough** [comment]
It seems there is also a bug and outlays are not being correctly updated

**Comment by farscapian** [comment]
I think this issue is closed in the latest release. This behavior us by design. Outlays all get updated first. Then outlays only go down upon successful payout.
