### ISSUE TITLE
Prisms can have ONE or MORE members.

### ISSUE THREAD

**Issue by farscapian** [gudnuf/bolt12-prism#52]
According to [gigi's prism post](https://dergigi.com/2023/03/12/lightning-prisms/): "a prism has one or multiple recipients". The current code has a prism consisting of at least two members. I agree with gigi, a Prism is simply a layer of payment indirection.

**Comment by gudnuf** [comment]
as of v2 f8d7da01103be434bb2ace7d15586e408d0542fc prisms can have 1 or more
