### ISSUE TITLE
Feature Request: External Prism Execution

### ISSUE THREAD

**Issue by farscapian** [gudnuf/bolt12-prism#59]
It would be nice if the prism payment logic could be invoked externally, for example by another plugin. Currently the only way to invoke the prism payment logic is by paying a BOLT12 invoice. 

Probably the easiest way to do this is add an rpc method: prism-execute that takes a PRISM_ID (the prism to execute), and AMOUNT (msats), and a LABEL that can be used to tie the payment execution back to a source event.

**Comment by gudnuf** [comment]
resolved

**Comment by gudnuf** [comment]
resolved with f8d7da01103be434bb2ace7d15586e408d0542fc and 85de9fa5ed563cdf41a406521a22a98ac6cc395c
