### ISSUE TITLE
Make sure invoice_payment is always the same

### ISSUE THREAD

**Issue by gudnuf** [gudnuf/bolt12-prism#6]
in on_payment we should validate that the offer_id is always provided from the invoice_payment event

**Comment by daGoodenough** [comment]
When an invoice is paid it has a label and it appears that the first part of the label is the offer_id
https://github.com/daGoodenough/bolt12-prism/blob/main/prism-plugin.py#L110C8-L110C58

**Comment by farscapian** [comment]
Closed in v2
