### ISSUE TITLE
Establish a "hierarchy" in the datastore with multiple keys

### ISSUE THREAD

**Issue by gudnuf** [gudnuf/bolt12-prism#62]
Currently, when creating prisms we create them with one key which makes it so that we have to list **all** items in the datastore to find one single prism. 

From  [the docs](https://docs.corelightning.org/reference/lightning-datastore):

"key is an array of values (though a single value is treated as a
one-element array), to form a hierarchy. Using the first element of
the key as the plugin name (e.g. [ "summary" ]) is recommended."

This makes we think the prism's do not need to be name paced with "prism" instead something like `datastore([prism, prismId])` could be used to create

**Comment by farscapian** [comment]
This is good timing, I'm circling back to the Prism v2 stuff now. I'll definitely poke around some more in the datastore stuff. I definitely want efficient queries, thanks for pointing that out. V2 is probably not ready for a merge request just yet. Found a bug here and there.

**Comment by gudnuf** [comment]
resolved with commit 14c6be64096a0c049cd6fdb4fcc99fde2545b2f1
